use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::config_model::{AppConfig, EffectiveConfig, MapEntry, SaveMode, SettingMetadata};
use crate::keybinding_editor::{render_map, validate_map_entry};
use crate::parser::resolve_include;
use crate::theme_browser::{is_theme_include, is_theme_setting_key, is_theme_wrapper_path};

const STARTER_CONFIG: &str = concat!(
    "# Generated by kitty-config-editor\n",
    "# No existing kitty.conf was found at startup, so a starter config was created.\n",
    "# Edit settings in the TUI, then save with `s` for a full config or `S` for minimal overrides.\n",
);

pub fn backup_config_root(main_file: &Path) -> Result<PathBuf> {
    let root = backup_source_root(main_file);
    let backup = root.with_extension("backup");
    if backup.exists() {
        if backup.is_dir() {
            let _ = fs::remove_dir_all(&backup);
        } else {
            let _ = fs::remove_file(&backup);
        }
    }
    copy_dir_recursive(&root, &backup)?;
    Ok(backup)
}

fn backup_source_root(main_file: &Path) -> PathBuf {
    main_file
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .to_path_buf()
}

fn copy_dir_recursive(from: &Path, to: &Path) -> Result<()> {
    fs::create_dir_all(to)?;
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let src = entry.path();
        let dst = to.join(entry.file_name());
        if src.is_dir() {
            copy_dir_recursive(&src, &dst)?;
        } else {
            fs::copy(&src, &dst)?;
        }
    }
    Ok(())
}

pub fn render_output(app: &AppConfig, mode: SaveMode) -> String {
    render_output_to_path(app, mode, &app.effective.main_file)
}

pub fn render_output_to_path(app: &AppConfig, mode: SaveMode, output_path: &Path) -> String {
    match mode {
        SaveMode::Full => render_full(app),
        SaveMode::Minimal => render_minimal(app, output_path),
    }
}

fn render_full(app: &AppConfig) -> String {
    let mut out = String::new();
    out.push_str(&app.effective.leading_block);
    append_main_file_includes(&mut out, app);

    let mut grouped: BTreeMap<String, Vec<&SettingMetadata>> = BTreeMap::new();
    for meta in &app.metadata {
        grouped.entry(meta.category.clone()).or_default().push(meta);
    }

    for (category, settings) in grouped {
        out.push_str(&format!("\n#: {} {{{{{{\n", category));
        for meta in settings {
            if uses_theme_wrapper(app) && is_theme_setting_key(&meta.key) {
                continue;
            }
            if let Some(value) = effective_value(app, &app.effective, meta) {
                if !value.trim().is_empty() {
                    out.push_str(&format!("{} {}\n", meta.key, value));
                }
            }
        }
    }

    if !app.edited_keymaps.is_empty() {
        out.push_str("\n#: Keyboard shortcuts {{{\n");
        for map in app
            .edited_keymaps
            .iter()
            .filter(|map| is_non_empty_map(map))
        {
            out.push_str(&format!("{}\n", render_map(map)));
        }
    }
    out
}

fn render_minimal(app: &AppConfig, output_path: &Path) -> String {
    let mut out = String::new();
    out.push_str("# Minimal Kitty overrides generated by kitty-config-editor\n");
    if theme_include_changed(app) {
        if let Some(include_line) = minimal_theme_include_line(app, output_path) {
            out.push_str(&include_line);
            out.push('\n');
        }
    }
    for meta in &app.metadata {
        if uses_theme_wrapper(app) && is_theme_setting_key(&meta.key) {
            continue;
        }
        if !app.is_changed(&meta.key) {
            continue;
        }
        if let Some(value) = app.edited_values.get(&meta.key) {
            if !value.trim().is_empty() {
                out.push_str(&format!("{} {}\n", meta.key, value));
            }
        }
    }
    if keymaps_changed(app) {
        for map in app
            .edited_keymaps
            .iter()
            .filter(|map| is_non_empty_map(map))
        {
            out.push_str(&format!("{}\n", render_map(map)));
        }
    }
    out
}

fn effective_value(
    app: &AppConfig,
    effective: &EffectiveConfig,
    meta: &SettingMetadata,
) -> Option<String> {
    if let Some(v) = app.edited_values.get(&meta.key) {
        return Some(v.clone());
    }
    if let Some(v) = effective.last_value(&meta.key) {
        return Some(v.value.clone());
    }
    meta.default_value.clone()
}

pub fn save_to_path(path: &Path, body: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

pub fn ensure_starter_config(path: &Path) -> Result<bool> {
    if path.exists() {
        return Ok(false);
    }

    save_to_path(path, STARTER_CONFIG)?;
    Ok(true)
}

#[allow(dead_code)]
pub fn replace_or_insert_theme_include(
    main_path: &Path,
    current: Option<&str>,
    new_include_line: &str,
) -> Result<()> {
    let text = fs::read_to_string(main_path)?;
    let body = replace_or_insert_theme_include_in_text(&text, current, new_include_line);
    fs::write(main_path, body)?;
    Ok(())
}

pub fn replace_or_insert_theme_include_in_text(
    text: &str,
    current: Option<&str>,
    new_include_line: &str,
) -> String {
    let mut out = Vec::new();
    let mut replaced = false;
    let current_norm = current.map(normalize_include_target);

    for raw in text.lines() {
        let trimmed = raw.trim();
        if let Some(existing_target) = trimmed.strip_prefix("include ") {
            let include_target = normalize_include_target(existing_target);
            let should_replace = current_norm
                .as_ref()
                .map(|current_target| *current_target == include_target)
                .unwrap_or_else(|| is_theme_include(existing_target));
            if should_replace && !replaced {
                out.push(new_include_line.to_string());
                replaced = true;
                continue;
            }
        }
        out.push(raw.to_string());
    }

    if !replaced {
        let insert_at = out
            .iter()
            .position(|line| {
                let trimmed = line.trim();
                !(trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("include "))
            })
            .unwrap_or(out.len());
        out.insert(insert_at, new_include_line.to_string());
    }

    let mut body = out.join("\n");
    if text.ends_with('\n') {
        body.push('\n');
    }
    body
}

fn normalize_include_target(path: &str) -> String {
    path.trim().trim_matches('"').replace('\\', "/")
}

fn append_main_file_includes(out: &mut String, app: &AppConfig) {
    let mut include_lines = Vec::new();
    let leading_includes = leading_block_includes(&app.effective.leading_block);
    let has_theme_in_leading_block = app
        .effective
        .leading_block
        .lines()
        .filter_map(|line| line.trim().strip_prefix("include "))
        .any(is_theme_include);

    if !has_theme_in_leading_block {
        if let Some(theme_line) = current_theme_include_line(app) {
            include_lines.push(theme_line);
        }
    }

    for include in app
        .effective
        .includes
        .iter()
        .filter(|include| include.source_file == app.effective.main_file)
    {
        if is_theme_include(&include.path) {
            continue;
        }

        let normalized = normalize_include_target(&include.path);
        if leading_includes
            .iter()
            .any(|existing| existing == &normalized)
        {
            continue;
        }
        include_lines.push(include.raw.trim().to_string());
    }

    if include_lines.is_empty() {
        return;
    }

    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    for line in include_lines {
        out.push_str(&line);
        out.push('\n');
    }
}

fn leading_block_includes(leading_block: &str) -> Vec<String> {
    leading_block
        .lines()
        .filter_map(|line| line.trim().strip_prefix("include "))
        .map(normalize_include_target)
        .collect()
}

fn current_theme_include_line(app: &AppConfig) -> Option<String> {
    app.current_theme_include
        .as_deref()
        .map(render_include_line)
}

fn minimal_theme_include_line(app: &AppConfig, output_path: &Path) -> Option<String> {
    if output_path == app.effective.main_file && uses_theme_wrapper(app) {
        current_theme_include_line(app)
    } else if let Some(path) = app.pending_theme_path.as_ref() {
        Some(render_include_line(&path.display().to_string()))
    } else {
        current_theme_include_line(app)
    }
}

fn theme_include_changed(app: &AppConfig) -> bool {
    let original = original_theme_include(app);
    if let Some(path) = app.pending_theme_path.as_ref() {
        let desired = normalize_include_target(&path.display().to_string());
        match original {
            Some(include) if is_theme_wrapper_path(include) => true,
            Some(include) => normalize_include_target(include) != desired,
            None => true,
        }
    } else {
        app.current_theme_include.as_deref() != original
    }
}

fn keymaps_changed(app: &AppConfig) -> bool {
    let original = app
        .effective
        .keymaps
        .iter()
        .filter(|map| is_non_empty_map(map))
        .map(render_map)
        .collect::<Vec<_>>();
    let edited = app
        .edited_keymaps
        .iter()
        .filter(|map| is_non_empty_map(map))
        .map(render_map)
        .collect::<Vec<_>>();
    original != edited
}

pub fn uses_theme_wrapper(app: &AppConfig) -> bool {
    app.current_theme_include
        .as_deref()
        .is_some_and(is_theme_wrapper_path)
}

fn is_non_empty_map(map: &MapEntry) -> bool {
    validate_map_entry(&map.shortcut, &map.action).is_ok()
}

fn render_include_line(path: &str) -> String {
    if path.chars().any(char::is_whitespace) {
        format!("include \"{}\"", path.replace('"', "\\\""))
    } else {
        format!("include {}", path)
    }
}

fn original_theme_include(app: &AppConfig) -> Option<&str> {
    app.effective
        .includes
        .iter()
        .rev()
        .find(|include| is_theme_include(&include.path))
        .map(|include| include.path.as_str())
}

pub fn write_selected_theme_artifact(
    app: &AppConfig,
    main_output_path: &Path,
) -> Result<Option<PathBuf>> {
    if !uses_theme_wrapper(app) {
        return Ok(None);
    }

    let wrapper_include = app
        .current_theme_include
        .as_deref()
        .unwrap_or("current-theme.conf");
    let wrapper_path = resolve_include(main_output_path, wrapper_include);
    let body = render_theme_artifact(app);
    save_to_path(&wrapper_path, &body)?;
    Ok(Some(wrapper_path))
}

pub fn render_theme_artifact(app: &AppConfig) -> String {
    let mut out = String::from("# Editable theme overrides generated by kitty-config-editor\n");
    for meta in &app.metadata {
        if !is_theme_setting_key(&meta.key) {
            continue;
        }
        if let Some(value) = effective_value(app, &app.effective, meta) {
            if !value.trim().is_empty() {
                out.push_str(&format!("{} {}\n", meta.key, value));
            }
        }
    }
    out
}

#[allow(dead_code)]
fn _maps_to_lines(maps: &[MapEntry]) -> Vec<String> {
    maps.iter().map(render_map).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config_model::{
        AppConfig, DiffLine, EditTarget, EffectiveConfig, Focus, IncludeLine, KeymapField, Mode,
        SearchTarget, SettingValue, ShortcutView, ThemeEntry, ValueType,
    };
    use std::collections::HashMap;
    use tempfile::tempdir;

    fn app() -> AppConfig {
        let meta = SettingMetadata {
            key: "font_size".into(),
            category: "Fonts".into(),
            description: String::new(),
            default_value: Some("11.0".into()),
            examples: vec![],
            enum_choices: vec![],
            repeatable: false,
            value_type: ValueType::Number,
            order: 0,
        };
        let mut values = HashMap::new();
        values.insert(
            "font_size".into(),
            vec![SettingValue {
                key: "font_size".into(),
                value: "12.0".into(),
                source_file: PathBuf::from("kitty.conf"),
                line_no: 1,
            }],
        );
        AppConfig {
            metadata: vec![meta.clone()],
            metadata_by_key: HashMap::from([(meta.key.clone(), meta)]),
            effective: EffectiveConfig {
                values,
                keymaps: vec![],
                includes: vec![],
                leading_block: "# header\n".into(),
                main_file: PathBuf::from("kitty.conf"),
            },
            default_keymaps: vec![],
            edited_values: HashMap::new(),
            edited_keymaps: vec![],
            selected_category: 0,
            selected_setting: 0,
            categories: vec!["Fonts".into()],
            search_query: String::new(),
            search_target: SearchTarget::Settings,
            search_results: vec![0],
            theme_query: String::new(),
            mode: Mode::Browse,
            focus: Focus::Settings,
            edit_buffer: String::new(),
            edit_target: Some(EditTarget::Setting("font_size".into())),
            enum_index: 0,
            keymap_field: KeymapField::Shortcut,
            detail_scroll: 0,
            diff_scroll: 0,
            status: String::new(),
            diff_lines: vec![DiffLine {
                kind: crate::config_model::DiffKind::Same,
                text: String::new(),
            }],
            themes: vec![ThemeEntry {
                name: "x".into(),
                path: PathBuf::from("x.conf"),
                preview: vec![],
            }],
            themes_dir: None,
            current_theme_artifact: PathBuf::from("current-theme.conf"),
            selected_theme: 0,
            shortcut_view: ShortcutView::Custom,
            shortcut_query: String::new(),
            selected_shortcut: 0,
            pending_quit: false,
            current_theme_include: None,
            pending_theme_path: None,
            theme_edit_save_path: None,
            theme_preview_active: false,
            live_theme_edit: false,
        }
    }

    #[test]
    fn renders_minimal_only_changed() {
        let mut app = app();
        app.edited_values.insert("font_size".into(), "13.0".into());
        let text = render_output(&app, SaveMode::Minimal);
        assert!(text.contains("font_size 13.0"));
    }

    #[test]
    fn normalizes_include_paths() {
        assert_eq!(
            normalize_include_target("\"themes/gruvbox.conf\""),
            "themes/gruvbox.conf"
        );
    }

    #[test]
    fn backup_stays_inside_kitty_dir_scope() {
        assert_eq!(
            backup_source_root(Path::new("/home/rabbit/.config/kitty/kitty.conf")),
            PathBuf::from("/home/rabbit/.config/kitty")
        );
    }

    #[test]
    fn inserts_theme_include_before_first_setting() {
        let original = "# header\nfont_size 12.0\n";
        let rewritten =
            replace_or_insert_theme_include_in_text(original, None, "include themes/gruvbox.conf");
        assert_eq!(
            rewritten,
            "# header\ninclude themes/gruvbox.conf\nfont_size 12.0\n"
        );
    }

    #[test]
    fn minimal_render_keeps_wrapper_for_main_file() {
        let mut app = app();
        app.current_theme_include = Some("current-theme.conf".into());
        app.pending_theme_path = Some(PathBuf::from("/tmp/themes/gruvbox.conf"));
        let text = render_output(&app, SaveMode::Minimal);
        assert!(text.contains("include current-theme.conf"));
        assert!(!text.contains("include /tmp/themes/gruvbox.conf"));
    }

    #[test]
    fn minimal_render_uses_pending_theme_path_for_external_output() {
        let mut app = app();
        app.current_theme_include = Some("current-theme.conf".into());
        app.pending_theme_path = Some(PathBuf::from("/tmp/themes/gruvbox.conf"));
        let text = render_output_to_path(
            &app,
            SaveMode::Minimal,
            Path::new("/tmp/kitty-overrides.conf"),
        );
        assert!(text.contains("include /tmp/themes/gruvbox.conf"));
    }

    #[test]
    fn writes_selected_theme_into_wrapper_include() {
        let dir = tempdir().expect("tempdir");
        let main_path = dir.path().join("kitty.conf");
        let theme_path = dir.path().join("themes").join("gruvbox.conf");
        fs::create_dir_all(theme_path.parent().expect("theme dir")).expect("create theme dir");
        fs::write(&theme_path, "foreground #ebdbb2\n").expect("write theme");
        fs::write(&main_path, "include current-theme.conf\n").expect("write main");

        let mut app = app();
        let theme_meta = SettingMetadata {
            key: "foreground".into(),
            category: "Colors".into(),
            description: String::new(),
            default_value: None,
            examples: vec![],
            enum_choices: vec![],
            repeatable: false,
            value_type: ValueType::Color,
            order: 1,
        };
        app.metadata.push(theme_meta.clone());
        app.metadata_by_key
            .insert(theme_meta.key.clone(), theme_meta);
        app.effective.main_file = main_path.clone();
        app.effective.values.insert(
            "foreground".into(),
            vec![SettingValue {
                key: "foreground".into(),
                value: "#ebdbb2".into(),
                source_file: PathBuf::from("current-theme.conf"),
                line_no: 1,
            }],
        );
        app.effective.includes = vec![IncludeLine {
            raw: "include current-theme.conf".into(),
            path: "current-theme.conf".into(),
            source_file: main_path.clone(),
            line_no: 1,
        }];
        app.current_theme_include = Some("current-theme.conf".into());
        app.pending_theme_path = Some(theme_path);

        let written = write_selected_theme_artifact(&app, &main_path).expect("write artifact");
        let wrapper_path = written.expect("wrapper path");
        assert_eq!(wrapper_path, dir.path().join("current-theme.conf"));
        let body = fs::read_to_string(wrapper_path).expect("read wrapper");
        assert!(body.contains("foreground #ebdbb2"));
    }

    #[test]
    fn full_render_skips_theme_settings_when_wrapper_is_active() {
        let mut app = app();
        let theme_meta = SettingMetadata {
            key: "foreground".into(),
            category: "Colors".into(),
            description: String::new(),
            default_value: None,
            examples: vec![],
            enum_choices: vec![],
            repeatable: false,
            value_type: ValueType::Color,
            order: 1,
        };
        app.metadata.push(theme_meta.clone());
        app.metadata_by_key
            .insert(theme_meta.key.clone(), theme_meta);
        app.effective.values.insert(
            "foreground".into(),
            vec![SettingValue {
                key: "foreground".into(),
                value: "#ffffff".into(),
                source_file: PathBuf::from("current-theme.conf"),
                line_no: 1,
            }],
        );
        app.current_theme_include = Some("current-theme.conf".into());

        let text = render_output(&app, SaveMode::Full);
        assert!(!text.contains("foreground #ffffff"));
    }

    #[test]
    fn renders_theme_artifact_from_effective_theme_values() {
        let mut app = app();
        let theme_meta = SettingMetadata {
            key: "foreground".into(),
            category: "Colors".into(),
            description: String::new(),
            default_value: None,
            examples: vec![],
            enum_choices: vec![],
            repeatable: false,
            value_type: ValueType::Color,
            order: 1,
        };
        app.metadata.push(theme_meta.clone());
        app.metadata_by_key
            .insert(theme_meta.key.clone(), theme_meta);
        app.effective.values.insert(
            "foreground".into(),
            vec![SettingValue {
                key: "foreground".into(),
                value: "#ffffff".into(),
                source_file: PathBuf::from("current-theme.conf"),
                line_no: 1,
            }],
        );

        let text = render_theme_artifact(&app);
        assert!(text.contains("foreground #ffffff"));
    }

    #[test]
    fn creates_starter_config_when_missing() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("kitty").join("kitty.conf");

        let created = ensure_starter_config(&path).expect("create starter");
        assert!(created);

        let body = fs::read_to_string(path).expect("read starter");
        assert!(body.contains("Generated by kitty-config-editor"));
    }

    #[test]
    fn does_not_overwrite_existing_config_when_ensuring_starter() {
        let dir = tempdir().expect("tempdir");
        let path = dir.path().join("kitty.conf");
        fs::write(&path, "font_size 14.0\n").expect("write config");

        let created = ensure_starter_config(&path).expect("ensure starter");
        assert!(!created);
        assert_eq!(
            fs::read_to_string(path).expect("read config"),
            "font_size 14.0\n"
        );
    }
}
